### Теперь займемся подготовкой спаршенного датасета
* Разберемся с пропусками
* Преобразуем имеющиеся признаки и выведем новые
* Сформируем финальное описание признаков датасета

In [102]:
import pandas as pd
df_final = pd.read_csv("../../data/df_final.csv")

In [103]:
df_final

,steam_id,game_name,game_description_snippet,game_price,found_game_price,all_language_reviews_type,all_language_reviews_count,has_russian_reviews,all_russian_reviews_type,all_russian_reviews_count,...,igdb_id,type,first_release_date,rating,rating_count,total_rating,total_rating_count,popularity_igdb,popularity_steam,popularity_twitch
0,1313940,My Holiday 2,This is the second part of the long holiday of...,259 руб.,1.0,Очень положительные,106.0,0.0,NaN,NaN,...,150866,NaN,2020-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1902870,Vertical Kingdom,Возродите былое величие Империи в этой карточн...,710 руб.,1.0,В основном положительные,111.0,0.0,NaN,NaN,...,202602,"GOG, Nintendo",2024-04-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1071940,Streamer's Life,"Игра в жанре RPG-Simulation, в которой вам пре...",NaN,0.0,В основном положительные,139.0,0.0,NaN,NaN,...,124447,NaN,2019-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1706570,Chupacabras: Night Hunt,Hunt the chupacabras alone or with your friend...,99 руб.,1.0,В основном положительные,124.0,0.0,NaN,NaN,...,163904,NaN,2021-08-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1085150,Golf Defied,"Физика и механики нового поколения, мультиплее...",Бесплатные,1.0,Смешанные,175.0,0.0,NaN,NaN,...,118634,NaN,2019-03-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25734,1547900,Active Mummy,"Active Mummy — динамичный 2D-платформер, в кот...",210 руб.,1.0,Положительные,20.0,0.0,NaN,NaN,...,156747,NaN,2021-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25735,2238360,You Have No Time,Rev up your inner speedster in this high-octan...,165 руб.,1.0,Положительные,13.0,0.0,NaN,NaN,...,244854,NaN,2023-11-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25736,1490030,Cyber Dodge,Cyber Dodge is a skill-based Runner and a Die ...,61 руб.,1.0,Обзоров пользователей: 3,3.0,0.0,NaN,NaN,...,159989,NaN,2021-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25737,1855190,Vektor Z,Vektor Z brings fast and furious retro space b...,280 руб.,1.0,Обзоров пользователей: 2,2.0,0.0,NaN,NaN,...,186672,NaN,2022-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25738,632130,Set 'N Det,Решайте головоломки с помощью взрывов! Казуаль...,NaN,0.0,Обзоров пользователей: 2,2.0,0.0,NaN,NaN,...,186861,Steam,2022-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 25739 entries, 0 to 25738
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   steam_id                    25739 non-null  int64
 1   game_name                   25739 non-null  str
 2   game_description_snippet    25217 non-null  str
 3   game_price                  19831 non-null  str
 4   found_game_price            24785 non-null  float64
 5   all_language_reviews_type   24418 non-null  str
 6   all_language_reviews_count  24418 non-null  float64
 7   has_russian_reviews         24785 non-null  float64
 8   all_russian_reviews_type    1543 non-null   str
 9   all_russian_reviews_count   1543 non-null   float64
 10  steam_app_url               24785 non-null  str
 11  support_ru_region           24785 non-null  float64
 12  igdb_id                     25739 non-null  int64
 13  type                        12909 non-null  str
 14  first_release_date          25404 non-null  str
 15  rating                      10140 non-null  float64
 16  rating_count                10140 non-null  float64
 17  total_rating                10576 non-null  float64
 18  total_rating_count          10576 non-null  float64
 19  popularity_igdb             3905 non-null   float64
 20  popularity_steam            4282 non-null   float64
 21  popularity_twitch           437 non-null    float64
dtypes: float64(12), int64(2), str(8)
memory usage: 4.3 MB

## Посмотрим на неудачно спаршенные игры

Посмотрев на вывод .info() по датасету можно заметить, что у нас есть ряд признаков, где у всех non-null значений по 24785. В частности, это бинарные T/F признаки found_game_price, has_russian_reviews, support_ru_region. То есть парсер не то что не смог найти значения или нет, он не смог определить/ответить есть они или нет.

In [105]:
print(f'{df_final['found_game_price'].isna().sum() / df_final.shape[0] * 100}%')

3.7064377015424066%

И т.к. этих пропусков всего 3.7%, то можно их просто удалить

In [106]:
df_final = df_final.dropna(subset=['found_game_price'])
df_final.info()

<class 'pandas.DataFrame'>
Index: 24785 entries, 0 to 25738
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   steam_id                    24785 non-null  int64
 1   game_name                   24785 non-null  str
 2   game_description_snippet    24764 non-null  str
 3   game_price                  19831 non-null  str
 4   found_game_price            24785 non-null  float64
 5   all_language_reviews_type   24418 non-null  str
 6   all_language_reviews_count  24418 non-null  float64
 7   has_russian_reviews         24785 non-null  float64
 8   all_russian_reviews_type    1543 non-null   str
 9   all_russian_reviews_count   1543 non-null   float64
 10  steam_app_url               24785 non-null  str
 11  support_ru_region           24785 non-null  float64
 12  igdb_id                     24785 non-null  int64
 13  type                        12402 non-null  str
 14  first_release_date          24470 non-null  str
 15  rating                      9954 non-null   float64
 16  rating_count                9954 non-null   float64
 17  total_rating                10369 non-null  float64
 18  total_rating_count          10369 non-null  float64
 19  popularity_igdb             3778 non-null   float64
 20  popularity_steam            4105 non-null   float64
 21  popularity_twitch           431 non-null    float64
dtypes: float64(12), int64(2), str(8)
memory usage: 4.3 MB

Теперь у нас количество non-null значений в тех столбцах равно количеству строк в датасете

## Начнем с обработки колонки с ценой

Если у нас была найдена цена, то в рублях и тогда формат записи цены будет, к примеру: 165 руб.

Проверим, действительно ли везде рубли и можем ли мы тогда при наличии более 1 элемента после разделения по пробелу - удалить это обозначение валюты

In [107]:
df_final['game_price'].str.split(' ').str[1].value_counts()

game_price
руб.           16966
to                50
To                 4
WARMACHINE:        1
Name: count, dtype: int64

Посмотрим что за 55 строк с "to", "To" и "WARMACHINE"

In [108]:
df_final[df_final['game_price'].str.contains('to')]

,steam_id,game_name,game_description_snippet,game_price,found_game_price,all_language_reviews_type,all_language_reviews_count,has_russian_reviews,all_russian_reviews_type,all_russian_reviews_count,...,igdb_id,type,first_release_date,rating,rating_count,total_rating,total_rating_count,popularity_igdb,popularity_steam,popularity_twitch
988,299420,CubeGun,A Sandbox Multiplayer Airship Shooting Game.De...,Free to Play,1.0,Смешанные,321.0,0.0,NaN,NaN,...,17372,NaN,2014-05-21,50.000000,0.0,50.000000,0.0,7.848961e-07,0.000010,NaN
1049,266030,DRAKERZ-Confrontation,The Trading Card Game in Augmented Reality.,Free to Play,1.0,Смешанные,259.0,0.0,NaN,NaN,...,16876,NaN,2014-05-19,NaN,NaN,NaN,NaN,NaN,0.000009,NaN
1185,365050,Escape,Escape is a simple 2D game with 35 levels alre...,Free to Play,1.0,Смешанные,290.0,0.0,NaN,NaN,...,35380,NaN,2015-04-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8678,250420,8BitMMO,8BitMMO is a retro-style 2D massively multipla...,Free to Play,1.0,Смешанные,4321.0,1.0,Смешанные,350.0,...,30232,NaN,2015-01-26,50.000000,2.0,50.000000,2.0,9.418753e-06,0.000137,NaN
8682,365270,Shadow Hunter,Shadow Hunter is a casual deductive puzzle gam...,Free to Play,1.0,Смешанные,73.0,0.0,NaN,NaN,...,35386,Steam,2015-04-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10357,201210,Pox Nora,Delve into classic turn-based strategy gaming ...,Free to Play,1.0,В основном положительные,882.0,0.0,NaN,NaN,...,9595,NaN,2004-08-01,NaN,NaN,NaN,NaN,2.653102e-05,0.000025,NaN
10687,340810,Deepworld,Deepworld is a massively-multiplayer 2D crafti...,Free to Play,1.0,Смешанные,737.0,0.0,NaN,NaN,...,35979,NaN,2015-04-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10781,360870,Ultimate Tic-Tac-Toe,Ultimate Tic-Tac-Toe takes the classic game of...,Free to Play,1.0,Очень положительные,1542.0,0.0,NaN,NaN,...,35501,NaN,2015-04-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12026,343740,InMind VR,InMind is a short scientific adventure with ar...,Free to Play,1.0,В основном положительные,432.0,0.0,NaN,NaN,...,19024,NaN,2015-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12047,361630,404Sight,404Sight is a free game made in support of net...,Free to Play,1.0,Очень положительные,1761.0,0.0,NaN,NaN,...,19389,NaN,2015-04-16,59.847319,6.0,59.847319,6.0,NaN,NaN,NaN
12198,338810,Demise of Nations,"Demise of Nations это 4Х пошаговая стратегия, ...",Free to Play,1.0,Очень положительные,542.0,0.0,NaN,NaN,...,36066,"Steam, Bluesky, Discord, Twitter",2015-04-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14568,364450,Freshman Year,Freshman Year is a vignette game about an ordi...,Free to Play,1.0,Смешанные,216.0,0.0,NaN,NaN,...,35405,Official Website,2015-04-20,NaN,NaN,NaN,NaN,7.848961e-07,0.000007,NaN
15224,346250,The Old Tree,The Old Tree is a short free-to-play cinematic...,Free to Play,1.0,Очень положительные,3312.0,1.0,Очень положительные,283.0,...,24610,NaN,2012-02-24,77.997638,7.0,68.998819,8.0,NaN,NaN,NaN
15542,294160,Galcon 2: Galactic Conquest,Galcon 2 is a demolition derby in space! Send ...,Free to Play,1.0,Очень положительные,865.0,0.0,NaN,NaN,...,36325,NaN,2014-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17096,99900,Spiral Knights,Вступайте в ряды игроков Spiral Knights. Оказа...,Free to Play,1.0,Очень положительные,23936.0,1.0,Очень положительные,1756.0,...,9265,"Facebook, YouTube",2011-04-04,61.669706,30.0,56.334853,31.0,NaN,NaN,NaN
17107,262410,World of Guns: Gun Disassembly,World of Guns: Guns Disassembly - настоящий ор...,Free to Play,1.0,Очень положительные,19644.0,1.0,Очень положительные,3319.0,...,7555,"Twitch, Twitter, YouTube, Instagram, Community...",2014-05-21,65.872255,14.0,65.872255,14.0,NaN,NaN,NaN
17132,242720,GunZ 2: The Second Duel,GunZ 2: the Second Duel is a free-to-play 3D T...,Free to Play,1.0,Смешанные,10632.0,1.0,В основном положительные,1116.0,...,16558,NaN,2014-04-04,40.503697,10.0,40.503697,10.0,NaN,NaN,NaN
17139,248570,Toribash,Toribash - это инновационный бесплатный пошаго...,Free to Play,1.0,Очень положительные,16781.0,1.0,Очень положительные,1851.0,...,1875,NaN,2006-03-01,67.473278,26.0,67.473278,26.0,6.510606e-05,0.000344,9.651292e-08
17159,212070,Star Conflict,Star Conflict — Это динамичный MMO экшн-симуля...,Free to Play,1.0,В основном положительные,15094.0,1.0,В основном положительные,4428.0,...,3210,NaN,2012-07-24,77.964304,9.0,77.964304,9.0,NaN,NaN,NaN
17201,206500,AirMech,AirMech® Strike is a fast paced Action-RTS gam...,Free to Play,1.0,Очень положительные,10818.0,1.0,Очень положительные,1438.0,...,1365,NaN,2018-03-30,36.093926,13.0,36.093926,13.0,8.154414e-05,0.000234,0.000000e+00
17236,214420,Gear Up,Feel the adrenaline as you control your unique...,Free to Play,1.0,В основном положительные,8348.0,1.0,В основном положительные,1146.0,...,15311,NaN,2015-01-28,80.000000,3.0,80.000000,3.0,NaN,NaN,NaN
17239,24200,DC Universe™ Online,"...сражения эпических масштабов, новые легенда...",Free to Play,1.0,Очень положительные,21697.0,1.0,Очень положительные,1596.0,...,576,NaN,2011-01-11,63.259002,65.0,68.486644,72.0,2.498225e-04,0.000803,1.703453e-05
17272,207230,ArcheBlade™,ArcheBlade is a free to play 3D multiplayer fi...,Free to Play,1.0,В основном положительные,7614.0,1.0,Очень положительные,1251.0,...,11664,NaN,2014-04-25,68.730230,6.0,68.730230,6.0,NaN,NaN,NaN
17335,383080,Sakura Clicker,The latest entry in the Sakura series is more ...,Free to Play,1.0,Очень положительные,14373.0,1.0,Очень положительные,1569.0,...,34950,NaN,2015-07-29,65.788040,14.0,65.788040,14.0,NaN,NaN,NaN
17421,329110,Gems of War - Puzzle RPG,"Добро пожаловать в Gems of Wars, – новый гибри...",Free to Play,1.0,В основном положительные,10700.0,1.0,В основном положительные,1441.0,...,9531,"Nintendo, Playstation, Google Play",2014-11-19,76.793144,28.0,76.793144,28.0,1.399350e-04,0.000792,2.171541e-06
18439,366960,SECTOR,SECTOR is a simple hardcore classic shooter ga...,Free to Play,1.0,В основном отрицательные,151.0,0.0,NaN,NaN,...,35347,NaN,2015-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19359,335330,Brick-Force,Brick-Force is a sandbox shooter that lets you...,Free to Play,1.0,Смешанные,3792.0,1.0,В основном отрицательные,301.0,...,18991,NaN,2012-07-12,40.000000,1.0,40.000000,1.0,NaN,NaN,NaN
19377,317360,Double Action: Boogaloo,Double Action is a free stylish multiplayer ga...,Free to Play,1.0,Очень положительные,11403.0,1.0,Очень положительные,1299.0,...,17723,NaN,2014-09-04,78.912334,5.0,78.912334,5.0,NaN,NaN,NaN
19436,298240,War Trigger 3,"Destroy, smash and blast your way to victory! ...",Free to Play,1.0,Смешанные,8165.0,1.0,Смешанные,934.0,...,17353,NaN,2015-04-05,50.000000,1.0,50.000000,1.0,8.633857e-06,0.000272,NaN
19437,298240,War Trigger 3,"Destroy, smash and blast your way to victory! ...",Free to Play,1.0,Смешанные,8165.0,1.0,Смешанные,934.0,...,17353,NaN,2015-04-05,50.000000,1.0,50.000000,1.0,8.633857e-06,0.000272,NaN
19464,212800,Super Crate Box,Vlambeer's SUPER CRATE BOX is coming to bring ...,Free to Play,1.0,Очень положительные,6444.0,1.0,Очень положительные,313.0,...,9945,NaN,2010-10-22,66.197492,16.0,79.348746,18.0,3.766491e-05,0.000128,NaN
19511,257730,Infinity Wars: Animated Trading Card Game,Outplay your opponent with simultaneous turns ...,Free to Play,1.0,В основном положительные,3463.0,0.0,NaN,NaN,...,16732,NaN,2014-08-05,70.000000,3.0,70.000000,3.0,NaN,NaN,NaN
19520,317470,Cubic Castles,"Your blocks, your castle, your world! Build an...",Free to Play,1.0,В основном положительные,4268.0,1.0,В основном положительные,260.0,...,17727,NaN,2014-08-07,60.000000,3.0,60.000000,3.0,NaN,NaN,NaN
19610,351640,Eternal Senia,Thoughts and expectations ARPG,Free to Play,1.0,Крайне положительные,12018.0,1.0,Очень положительные,451.0,...,35715,Twitch,2015-06-18,71.569400,13.0,71.569400,13.0,NaN,NaN,NaN
19644,305260,Battle Islands,"Battle friends over air, land and sea in this ...",Free to Play,1.0,В основном положительные,3436.0,1.0,В основном положительные,283.0,...,17502,Steam,2013-11-01,50.000000,4.0,50.000000,4.0,NaN,NaN,NaN
19672,200210,Realm of the Mad God Exalt,Embark on an exhilarating journey into the pix...,Free to Play,1.0,Очень положительные,47377.0,1.0,Очень положительные,2366.0,...,8188,"Instagram, Discord, Subreddit, Community Wiki,...",2011-06-20,60.105021,45.0,72.552510,47.0,1.392552e-04,0.001582,1.857874e-05
19673,372800,RPG MO,RPG MO is a nostalgic MMORPG that reminds of U...,Free to Play,1.0,В основном положительные,2940.0,1.0,В основном положительные,250.0,...,35161,NaN,2015-08-18,59.383129,5.0,59.383129,5.0,NaN,NaN,NaN
19897,321840,Rising Angels: Reborn,"Despite determination and skill, Natalie Pucci...",Free to Play,1.0,Очень положительные,587.0,0.0,NaN,NaN,...,17817,NaN,2014-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20486,348700,Walkover,It is WAR!Team up with your comrades to stand ...,Free to Play,1.0,Смешанные,136.0,0.0,NaN,NaN,...,35787,NaN,2015-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21747,327640,CaesarIA,CaesarIA - это ремейк олдскульной экономическо...,Free to Play,1.0,Смешанные,1456.0,0.0,NaN,NaN,...,17927,NaN,2015-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21792,213650,Dwarfs - F2P,"Dwarfs!? is an addictive, fast paced arcade-li...",Free to Play,1.0,Очень положительные,1692.0,0.0,NaN,NaN,...,90631,NaN,2012-10-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21814,342980,Destination Sol,Отправьтесь в путешествие на космическом кораб...,Free to Play,1.0,В основном положительные,1361.0,0.0,NaN,NaN,...,15737,NaN,2015-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21858,298160,Eldevin,Eldevin is the award winning indie story-drive...,Free to Play,1.0,В основном положительные,1787.0,0.0,NaN,NaN,...,17350,NaN,2014-11-05,50.000000,3.0,50.000000,3.0,NaN,NaN,NaN
22114,222520,Champions of Regnum,Choose your Realm and engage in the most dynam...,Free to Play,1.0,Смешанные,1224.0,0.0,NaN,NaN,...,16426,NaN,2013-01-03,72.089888,27.0,72.089888,27.0,1.088600e-04,0.000043,8.203598e-06
22179,346120,Boring Man - Online Tactical Stickman Combat,Battle other 2D stickfigures online while jump...,Free to Play,1.0,Очень положительные,5440.0,1.0,Очень положительные,314.0,...,35862,NaN,2014-04-04,80.000000,0.0,80.000000,0.0,NaN,NaN,NaN
24747,399520,Comedy Quest,Comedy Quest is a point and click adventure ga...,Free to Play,1.0,Очень положительные,301.0,0.0,NaN,NaN,...,34508,Steam,2015-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24873,365070,One Manga Day,Манга - японские комиксы. Стоп! Но раз комиксы...,Free to Play,1.0,Смешанные,966.0,0.0,NaN,NaN,...,35382,NaN,2015-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24948,353360,how do you Do It?,"""how do you Do It?"" puts players in the role o...",Free to Play,1.0,Очень положительные,2519.0,0.0,NaN,NaN,...,60443,NaN,2014-01-26,70.000000,2.0,70.000000,2.0,NaN,NaN,NaN
24992,334030,Epic Arena,Epic Arena — это бесплатная пошаговая 3D-страт...,Free to Play,1.0,Смешанные,301.0,0.0,NaN,NaN,...,36121,NaN,2015-05-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25211,352160,Curse of Mermos,"Curse of Mermos is a free, lighthearted hack a...",Free to Play,1.0,Смешанные,262.0,0.0,NaN,NaN,...,35678,Steam,2015-06-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
df_final[df_final['game_price'].str.contains('To')]

,steam_id,game_name,game_description_snippet,game_price,found_game_price,all_language_reviews_type,all_language_reviews_count,has_russian_reviews,all_russian_reviews_type,all_russian_reviews_count,...,igdb_id,type,first_release_date,rating,rating_count,total_rating,total_rating_count,popularity_igdb,popularity_steam,popularity_twitch
5966,348840,UFHO2,Play an alien navigating a maze of hexagons in...,Free To Play,1.0,Положительные,38.0,0.0,NaN,NaN,...,35793,NaN,2014-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19475,298260,Only If,Only If is a surreal first person adventure-pu...,Free To Play,1.0,Смешанные,5954.0,1.0,Смешанные,362.0,...,17354,NaN,2014-07-25,69.525071,18.0,74.762536,19.0,NaN,NaN,NaN
19531,263540,Villagers and Heroes,Лучшая 3D MMO-игра! Фэнтезийная RPG со сражени...,Free To Play,1.0,Смешанные,3428.0,1.0,Смешанные,437.0,...,16843,NaN,2014-03-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21807,290730,My Lands: Black Gem Hunting,My Lands – бесплатная реалтаймовая онлайн-стра...,Free To Play,1.0,Очень положительные,3308.0,1.0,Очень положительные,1875.0,...,10576,NaN,2014-09-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
df_final[df_final['game_price'].str.contains('WARMACHINE:')]

,steam_id,game_name,game_description_snippet,game_price,found_game_price,all_language_reviews_type,all_language_reviews_count,has_russian_reviews,all_russian_reviews_type,all_russian_reviews_count,...,igdb_id,type,first_release_date,rating,rating_count,total_rating,total_rating_count,popularity_igdb,popularity_steam,popularity_twitch
24973,253510,WARMACHINE: Tactics,Turn-based tactical combat set in the award-wi...,Play WARMACHINE: Tactics Demo,1.0,Смешанные,1160.0,0.0,NaN,NaN,...,16695,NaN,2014-10-04,50.0,1.0,50.0,1.0,0.000013,0.000044,5.308210e-07

Вышло, что первые два случая это бесплатные игры, а у одной игры неверно нашлась цена, но видно что там есть демо версия, а значит платная версия.

Для этой одной игры можно было не полениться и посмотреть вручную цену - 419 руб. Заменим пока у нее цену, а также посмотрим как еще обозначаются бесплатные игры

In [111]:
df_final.loc[24973, 'game_price'] = '419 руб.' # первое это индекс строки, второе уже имя столбца
df_final[df_final['steam_id'] == 253510]

,steam_id,game_name,game_description_snippet,game_price,found_game_price,all_language_reviews_type,all_language_reviews_count,has_russian_reviews,all_russian_reviews_type,all_russian_reviews_count,...,igdb_id,type,first_release_date,rating,rating_count,total_rating,total_rating_count,popularity_igdb,popularity_steam,popularity_twitch
24973,253510,WARMACHINE: Tactics,Turn-based tactical combat set in the award-wi...,419 руб.,1.0,Смешанные,1160.0,0.0,NaN,NaN,...,16695,NaN,2014-10-04,50.0,1.0,50.0,1.0,0.000013,0.000044,5.308210e-07

In [112]:
first_el_price = df_final['game_price'].str.split(' ').str[0].reset_index()
first_el_price['game_price'].value_counts()

game_price
Бесплатно     1966
42            1398
82            1236
200           1113
Бесплатные     844
              ...
346,85           1
977              1
71               1
3499             1
1020             1
Name: count, Length: 498, dtype: int64

Попробуем преобразовать все значения в числа, что не сможем - выведем

Также заметим, что нам здесь уже видно дробное число с зяпятой вместо точки для разделения целой и дробной частей. Заменим для начала запятые на точки. Сделаем это в исходном датасете

In [113]:
df_final['game_price'] = df_final['game_price'].str.replace(',', '.')

In [114]:
first_el_price = df_final['game_price'].str.split(' ').str[0].reset_index()
# https://stackoverflow.com/questions/73313363/how-to-deal-with-strings-on-a-numeric-column-in-pandas

first_el_price['game_price_nums'] = pd.to_numeric(first_el_price['game_price'], errors='coerce')

first_el_price.loc[first_el_price['game_price'].notna() & first_el_price['game_price_nums'].isna(), 'game_price'].value_counts()

game_price
Бесплатно     1966
Бесплатные     844
Free            54
Name: count, dtype: int64

Мы нашли три варианта обозначения бесплатной игры, где "Free" как первый элемент это для строк, которые были найдены раньше, где значения "Free to Play" и "Free To Play"

Заменим их все на 0, а также уберем "руб."

In [115]:
df_final['game_price'] = df_final['game_price'].str.replace('Бесплатно', '0')
df_final['game_price'] = df_final['game_price'].str.replace('Бесплатные', '0')
df_final['game_price'] = df_final['game_price'].str.replace('Free to Play', '0')
df_final['game_price'] = df_final['game_price'].str.replace('Free To Play', '0')
df_final['game_price'] = df_final['game_price'].str.replace('руб.', '')

Попробуем теперь применить pd.to_numeric уже в исходном df и без указания errors='coerce'. Если все пройдет без ошибок, знвчит все значения числовые, если будет ошибка то продолжим разбираться

In [116]:
df_final['game_price'] = pd.to_numeric(df_final['game_price'])

In [117]:
df_final['game_price'].dtype

dtype('float64')

Отлично, все значения преобразовались в число, в данном случае float

Проверим также верно ли указано наличие/отсутствие данных о цене в признаке found_game_price

In [118]:
not_found_game_price = df_final[df_final['found_game_price'] == 0]
not_found_game_price[not_found_game_price['game_price'].notna()]

Empty DataFrame
Columns: [steam_id, game_name, game_description_snippet, game_price, found_game_price, all_language_reviews_type, all_language_reviews_count, has_russian_reviews, all_russian_reviews_type, all_russian_reviews_count, steam_app_url, support_ru_region, igdb_id, type, first_release_date, rating, rating_count, total_rating, total_rating_count, popularity_igdb, popularity_steam, popularity_twitch]
Index: []

[0 rows x 22 columns]

In [119]:
not_found_game_price = df_final[df_final['found_game_price'] == 1]
not_found_game_price[not_found_game_price['game_price'].isna()]

Empty DataFrame
Columns: [steam_id, game_name, game_description_snippet, game_price, found_game_price, all_language_reviews_type, all_language_reviews_count, has_russian_reviews, all_russian_reviews_type, all_russian_reviews_count, steam_app_url, support_ru_region, igdb_id, type, first_release_date, rating, rating_count, total_rating, total_rating_count, popularity_igdb, popularity_steam, popularity_twitch]
Index: []

[0 rows x 22 columns]

Для тех строк, где указано что цена найдена - пропусков нет. Где не найдена - все пропуски. Делаем вывод что признак определился верно на этапе скрапинга.