In [65]:
import requests
import json
import pandas as pd
from dotenv import load_dotenv
import os

IGDB

Начнем с того, что попробуем взять igdb_id, igdb_secret, потом получить от них токен и попробовать с ним поработать для первичного анализа инди игр

Документация IGDB API- https://api-docs.igdb.com/

In [69]:
igdb_id = os.getenv('client_id')
igdb_secret = os.getenv('client_secret')

In [27]:
request = requests.post(url = f'https://id.twitch.tv/oauth2/token?client_id={igdb_id}&client_secret={igdb_secret}&grant_type=client_credentials')
request #получили токен, добавили в .env как access_token

In [70]:
access_token = os.getenv('access_token')

Имея датасет из 50к игр жанра Инди (имея их steam_id), получим их же id на igdb

Для начала попробуем получить 500 строк, если все будет в порядке, напишем цикл, который возьмет остальные нужные (так как в igdb можно брать максимум 500 строк за раз)

In [187]:
indie = pd.read_excel('indie_games.xlsx')
indie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52781 entries, 0 to 52780
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   steam_app_id  52781 non-null  int64
 1   name          52771 non-null  object
dtypes: int64(1), object(1)
memory usage: 824.8+ KB

In [188]:
ids = indie["steam_app_id"].astype(str).tolist()[:500]
uids = '","'.join(ids)
uids = '"' + uids + '"'


data = f'fields uid,game; where external_game_source = 1 & uid = ({uids}); limit 500;'
request_games_steam = requests.post('https://api.igdb.com/v4/external_games', headers={'Client-ID': igdb_id, 'Authorization': f'Bearer {access_token}'}, data=data)
res = request_games_steam.json()
res

map_df = pd.DataFrame(res)
map_df = map_df[["uid", "game"]].drop_duplicates(subset=["uid"])
map_df['uid'] = map_df['uid'].astype(int)

indie = indie.rename(columns ={'steam_app_id': 'uid'})
indie['uid'] = indie['uid'].astype(int)
out = indie.merge(map_df, on= 'uid', how= 'left')

In [189]:
out

           uid                     name      game
0       578080      PUBG: BATTLEGROUNDS   27789.0
1      1623730                 Palworld  151665.0
2       304930                 Unturned    7878.0
3       105600                 Terraria    1879.0
4       431960         Wallpaper Engine       NaN
...        ...                      ...       ...
52776  3591890                CombatBox       NaN
52777  3451960    101 Cats in New Delhi       NaN
52778  2656520          Mycelium Heaven       NaN
52779  1589920  Long Ago: A Puzzle Tale       NaN
52780  1513670                     Fono       NaN

[52781 rows x 3 columns]

In [ ]:
indie = indie.head(11_000).copy()
all = []

for i in range(0, len(indie), 500):
    ids = indie['uid'].iloc[i:i+500].astype(str).tolist()
    uids = '"' + '","'.join(ids) + '"'

    data = f'fields uid,game; where external_game_source = 1 & uid = ({uids}); limit 500;'
    request_games_steam = requests.post('https://api.igdb.com/v4/external_games', headers={'Client-ID': igdb_id, 'Authorization': f'Bearer {access_token}'}, data=data)
    res = request_games_steam.json()

    all += res
map_df = pd.DataFrame(all)
map_df = map_df[["uid", "game"]].drop_duplicates("uid")
map_df["uid"] = map_df["uid"].astype(int)

out = indie.merge(map_df, on="uid", how="left")
out

           uid                   name      game
0       578080    PUBG: BATTLEGROUNDS   27789.0
1      1623730               Palworld  151665.0
2       304930               Unturned    7878.0
3       105600               Terraria    1879.0
4       431960       Wallpaper Engine       NaN
...        ...                    ...       ...
10995   316840  The Sacred Tears TRUE    9483.0
10996   796440               Spaceguy   86438.0
10997   775960  The Tower of Beatrice   90417.0
10998   726020     Mission Ammunition   74371.0
10999   850820             祛魅·教化（祛魅1）   98330.0

[11000 rows x 3 columns]

Что мы получили? 
1) uid - id игры в стиме
2) name - название игры
3) game - id игры в igdb

In [196]:
out = out.dropna() #удалим пропуски, так как далее не сможем с ними ничего сделать в других эндпоинтах (пропуски в game)
print(out.isna().sum())
out.info()

uid     0
name    0
game    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 10781 entries, 0 to 10999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uid     10781 non-null  int64
 1   name    10781 non-null  object
 2   game    10781 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 336.9+ KB

In [212]:
out['game'] = out['game'].astype(int)
out.to_csv('igdb_steam_games.csv') 
out['game']

0         27789
1        151665
2          7878
3          1879
5         10233
          ...
10995      9483
10996     86438
10997     90417
10998     74371
10999     98330
Name: game, Length: 10781, dtype: int64

In [219]:
prob = out.head(500).copy()
prob
ids = prob['game'].astype(str).tolist()
ids_str = ','.join(ids)

data1 = f'''
fields id, name, rating, rating_count, total_rating, total_rating_count, first_release_date,
language_supports, summary; where id = ({ids_str}); limit 500;
'''
request_prob = requests.post('https://api.igdb.com/v4/games', headers={'Client-ID': igdb_id, 'Authorization': f'Bearer {access_token}'}, data=data1)

res =request_prob.json()
res

[{'id': 111,
  'first_release_date': 1283904000,
  'name': 'Amnesia: The Dark Descent',
  'rating': 77.95333920297041,
  'rating_count': 523,
  'summary': 'Amnesia: The Dark Descent is a survival horror video game by Frictional Games. The game features a protagonist named Daniel exploring a dark and foreboding castle, while trying to maintain his sanity by avoiding monsters and other terrifying obstructions. The game was critically well received.',
  'total_rating': 83.47666960148521,
  'total_rating_count': 525,
  'language_supports': [478453,
   478456,
   478457,
   478454,
   478455,
   478458,
   478459,
   478460,
   478461,
   536120,
   536122,
   536123,
   536124,
   536125,
   536126,
   536127]},
 {'id': 232,
  'first_release_date': 942192000,
  'name': 'Half-Life: Opposing Force',
  'rating': 79.91431228594388,
  'rating_count': 386,
  'summary': 'Opposing Force returns to the same setting as Half-Life, but instead portrays the events from the perspective of a U.S. Marine, one of the enemy characters in the original game. The player character, Adrian Shephard, is sent in to neutralize the Black Mesa Research Facility after a scientific mishap causes it to be invaded by aliens, but quickly finds that the Marines are outnumbered and slowly being beaten back by a second alien race and black operations units.',
  'total_rating': 74.95715614297194,
  'total_rating_count': 387,
  'language_supports': [604211, 604212, 604213, 604214]},
 {'id': 527,
  'first_release_date': 1321920000,
  'name': 'Serious Sam 3: BFE',
  'rating': 69.98346166723435,
  'rating_count': 172,
  'summary': 'Serious Sam 3: BFE is a first-person action shooter, a glorious throwback to the golden age of first-person shooters where men were men, cover was for amateurs and pulling the trigger made things go boom.\n\nServing as a prequel to the original game, Serious Sam: The First Encounter, Serious Sam 3 takes place during the Earth’s final struggle against Mental’s invading legions of beasts and mercenaries.',
  'total_rating': 70.40839750028384,
  'total_rating_count': 178,
  'language_supports': [409265,
   409267,
   409269,
   409272,
   409273,
   409275,
   409274,
   409271,
   409270,
   409276,
   409277,
   409282,
   409278,
   409286,
   409289,
   409291,
   409292,
   409293]},
 {'id': 576,
  'first_release_date': 1294704000,
  'name': 'DC Universe Online',
  'rating': 63.25900159306133,
  'rating_count': 65,
  'summary': 'DC Universe Online is a free-to-play superhero / supervillian MMORPG that lets players create their own unique tights-wearing hero or villain and roam the streets of places like Gotham City and Metropolis fighting or creating crime. Players fight alongside such iconic DC Comics characters as Superman and Batman, Lex Luthor and The Joker, and many others. Excellent physics help bring comic book action and combat to life, all under the creative direction of noted comic book artist Jim Lee.',
  'total_rating': 68.48664365367353,
  'total_rating_count': 72,
  'language_supports': [137259,
   137260,
   137261,
   137262,
   137263,
   75826,
   137264,
   137265,
   499133,
   499131,
   954310,
   954311,
   1161798,
   1161799,
   1161800,
   1161801,
   1161793,
   1161794,
   1161795,
   1161796,
   1161797]},
 {'id': 787,
  'first_release_date': 1128988800,
  'name': 'Serious Sam II',
  'rating': 71.57033256763481,
  'rating_count': 182,
  'summary': 'The iconic Serious Sam brings his trademark relentless intensity to this bigger, bolder, more colorful sequel to the classic Serious Sam: First and Second Encounters! Tasked with rescuing the universe one bullet at a time against overwhelming hordes of time traveling enemies, Serious Sam must battle through thick jungles, murky swamps, frozen tundra, and futuristic cities to bring down Mental and his vile armies. Serious Sam 2 is a shot of adrenaline to the hearts of first-person shooter fans across the world. This is serious!',
  'total_rating': 74.95183295048406,
  'total_rating_count': 185,
  'language_supports': [534874, 534875, 534873]},
 {'id': 885,
  'first_release_date': 1287532800,
  'name': 'Super Meat Boy',
  'rating': 82.54032107210338,
  'rating_count': 819,
  'summary': "Super Meat Boy is a tough-as-nails platformer where you play as an animated cube of meat who's trying to save his girlfriend (who happens to be made of bandages) from an evil fetus in a jar wearing a tux.",
  'total_rating': 83.89516053605169,
  'total_rating_count': 823,
  'language_supports': [32828, 32829, 493538, 493539, 493540, 493542, 493541]},
 {'id': 1281,
  'first_release_date': 1335830400,
  'name': 'Awesomenauts',
  'rating': 65.82892516082947,
  'rating_count': 71,
  'summary': "Two teams battle each other to take down the opposing sides turrets and base. There's multiple stages and some with hidden traps in the environment. Each team defends multiple lanes, and has to plan and coordinate properly to take down the other team.",
  'total_rating': 69.16446258041474,
  'total_rating_count': 79,
  'language_supports': [419678,
   419682,
   419683,
   419684,
   419685,
   419686,
   419677,
   419679,
   419680,
   419681]},
 {'id': 1331,
  'first_release_date': 1279670400,
  'name': 'Limbo',
  'rating': 81.06121748778483,
  'rating_count': 1560,
  'summary': 'Limbo is a black and white puzzle-platforming adventure. Players take the role of a young boy traveling through an eerie and treacherous world in an attempt to discover the fate of his sister.',
  'total_rating': 82.53060874389242,
  'total_rating_count': 1570,
  'language_supports': [8456,
   8457,
   8451,
   8453,
   8455,
   8459,
   8452,
   8454,
   8458,
   8446,
   8447,
   8448,
   8449,
   8450]},
 {'id': 1334,
  'first_release_date': 1375833600,
  'name': 'Brothers: A Tale of Two Sons',
  'rating': 81.32912338645122,
  'rating_count': 761,
  'summary': 'Brothers is presented from a third-person view overlooking the two brothers. The brothers are moved individually by two thumbsticks on the controller. The controller triggers also cause the respective brother to interact with the game world, such as talking to a non-player character or grabbing onto a ledge or object.\n\nThe older brother is the stronger of the two and can pull levers or boost his younger brother to higher spaces, while the younger one can pass between narrow bars. The player progresses by manipulating the two brothers at the same time to complete various puzzles, often requiring the player to manipulate both brothers to perform differing functions (such as one distracting a hostile non-player character while the other makes their way around).\n\nShould either brother fall from a great height or get injured, the game restarts at a recent checkpoint. All of the in-game dialogue is spoken in a fictional language, thus the story is conveyed through actions, gestures and expressions.',
  'total_rating': 82.38331169322561,
  'total_rating_count': 777,
  'language_supports': [196548,
   196530,
   163089,
   163099,
   163090,
   163092,
   163094,
   163095,
   163097,
   163098,
   163101,
   196534,
   196536,
   196538,
   196540,
   196542,
   196543,
   196544,
   196546,
   477375,
   517625]},
 {'id': 1335,
  'first_release_date': 1351555200,
  'name': 'Natural Selection 2',
  'rating': 77.84215548593593,
  'rating_count': 30,
  'summary': 'Natural Selection 2 is an immersive, multiplayer shooter that pits aliens against humans in a strategic and action-packed struggle for survival. It seamlessly combines shooter and RTS/strategy gameplay.',
  'total_rating': 81.42107774296797,
  'total_rating_count': 32,
  'language_supports': [541851,
   541852,
   541853,
   541854,
   541855,
   541856,
   541857,
   541858,
   541859,
   541860,
   541861,
   541862,
   541863,
   541864]},
 {'id': 1337,
  'first_release_date': 1348099200,
  'name': 'Torchlight II',
  'rating': 77.96211031069508,
  'rating_count': 309,
  'summary': 'Torchlight II features randomly generated dungeons and numerous types of monsters to fight for loot. Torchlight II is an action RPG as its predecessor, but features overland areas with multiple hub towns, and a longer campaign. Players are able to customize character appearance with choice of sex, face, hair style and hair color. Additionally, several elements from the first game return, such as pets and fishing.\nThe game features four playable character classes. Each class has 3 skill trees to choose from which enable customization within each class.',
  'total_rating': 81.78874746303984,
  'total_rating_count': 322,
  'language_supports': [30841,
   30842,
   30843,
   30844,
   30845,
   30846,
   30847,
   30848,
   30849,
   30850,
   30851,
   30852,
   30853,
   30854,
   499411,
   499412,
   499413,
   499415]},
 {'id': 1338,
  'first_release_date': 1444089600,
  'name': 'Prison Architect',
  'rating': 75.53766089758946,
  'rating_count': 188,
  'summary': 'The game is a top-down 2D construction and management simulation where the player takes control of building and running a prison. The player is responsible for managing various aspects of their prison including building cells and facilities, planning and connecting utilities, hiring and assigning staff, including a warden, guards, workers, and more. The player needs to recruit staff to unlock more aspects of the game. The player is also responsible for the finance, and keeping their inmates content.',
  'total_rating': 78.30729198725626,
  'total_rating_count': 200,
  'language_supports': [116875,
   116876,
   116877,
   116878,
   116880,
   116879,
   116881,
   116882,
   116868,
   116870,
   116869,
   116871,
   116873,
   116872,
   116874,
   475973,
   475978,
   475976,
   475980,
   475982,
   475986,
   475984,
   496825]},
 {'id': 1339,
  'first_release_date': 1113868800,
  'name': 'Psychonauts',
  'rating': 83.59737691859344,
  'rating_count': 401,
  'summary': 'Psychonauts is a platform-adventure game developed by Double Fine Productions and released in 2005. It follows Razputin “Raz” Aquato, a young psychic who runs away from the circus to attend a summer camp for aspiring psychonauts. Players explore imaginative levels set inside the minds of different characters, each reflecting their mental states. Gameplay combines platforming, combat, and the use of psychic abilities such as telekinesis and levitation. The game was praised for its creativity, humor, and distinctive art style.',
  'total_rating': 84.21535512596338,
  'total_rating_count': 407,
  'language_supports': [165958, 165959, 165960, 476796, 476797, 476798]},
 {'id': 1365,
  'first_release_date': 1522368000,
  'name': 'AirMech',
  'rating': 36.09392637622853,
  'rating_count': 13,
  'summary': 'AirMech is a fast paced Action-RTS game that can be played online competitively or cooperatively. Earn Kudos and Experience in battle and unlock a wide collection of AirMechs and Units while you practice the perfect strategy to emerge victorious!',
  'total_rating': 36.09392637622853,
  'total_rating_count': 13,
  'language_supports': [534585,
   534579,
   534580,
   534581,
   534582,
   534583,
   534587,
   534574,
   534575,
   534576,
   534577,
   534578,
   534589,
   534591,
   534592]},
 {'id': 1381,
  'first_release_date': 1318896000,
  'name': 'Payday: The Heist',
  'rating': 69.98091000381328,
  'rating_count': 145,
  'summary': 'Payday: The Heist is an action filled first person shooter that lets players take on the role of a hardened career criminal executing intense, dynamic heists in constant pursuit of the next “big score”. Load out with an array of weaponry and equipment. Navigate six high-stake heists with three other live or A.I. Co-Op partners in crime.',
  'total_rating': 71.24045500190664,
  'total_rating_count': 149,
  'language_supports': [373446, 373448, 373447, 373450, 373449, 373451]},
 {'id': 1384,
  'first_release_date': 1350950400,
  'name': 'Hotline Miami',
  'rating': 83.21637214050392,
  'rating_count': 1220,
  'summary': 'A top-down slasher/shooter with unlockable gameplay-altering masks and weapons, featuring a neon-flavoured electronic aesthetic, in which a hitman receives anonymous calls ordering him to travel to certain residences and crime dens and massacre those within, as he stumbles through unreal visions and inconsistencies without any answers to how, why or who.',
  'total_rating': 84.70818607025197,
  'total_rating_count': 1230,
  'language_supports': [126693,
   126694,
   126695,
   126696,
   126697,
   126698,
   126699,
   126700,
   126701,
   126702,
   126703,
   126704,
   126705,
   126706,
   480439,
   480440,
   480441,
   480442,
   480443,
   480445,
   480446,
   480447,
   827429,
   827430,
   827431,
   827432,
   827433,
   827434,
   827435,
   827436,
   827437,
   827438,
   827439,
   827440]},
 {'id': 1593,
  'first_release_date': 1427328000,
  'name': 'Pillars of Eternity',
  'rating': 80.13445713373417,
  'rating_count': 309,
  'summary': 'Prepare to be enchanted by a world where the choices you make and the paths you choose shape your destiny. Recapture the deep sense of exploration, the joy of a pulsating adventure, and the thrill of leading your own band of companions across a new fantasy realm and into the depths of monster-infested dungeons in search of lost treasures and ancient mysteries.\n\nSo gather your party, venture forth, and embrace adventure as you delve into a realm of wonder, nostalgia, and the excitement of classic RPGs with Obsidian’s Pillars of Eternity!',
  'total_rating': 80.56722856686709,
  'total_rating_count': 315,
  'language_supports': [68216,
   68202,
   68203,
   68204,
   68205,
   68206,
   68207,
   68209,
   68208,
   68210,
   68213,
   68211,
   68214,
   68212,
   68215,
   480067,
   480068,
   480069,
   480070,
   480071,
   480072]},
 {'id': 1875,
  'first_release_date': 1141171200,
  'name': 'Toribash',
  'rating': 68.4878615187757,
  'rating_count': 25,
  'summary': "Toribash is an innovative free-to-play online turn-based fighting game where you're able to design your own moves.\nComplete control over character's body, hundreds of game mods and bloody mess with full body dismemberment.",
  'total_rating': 68.4878615187757,
  'total_rating_count': 25,
  'language_supports': [451598, 451596, 451597, 451599, 451595]},
 {'id': 1879,
  'first_release_date': 1305504000,
  'name': 'Terraria',
  'rating': 82.45598409695157,
  'rating_count': 989,
  'summary': 'Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, machinery, and aesthetics? Perhaps you will choose instead to seek out ever-greater foes to test your mettle in combat? Maybe you will decide to construct your own city to house the host of mysterious allies you may encounter along your travels? In the World of Terraria, the choice is yours!',
  'total_rating': 81.72799204847578,
  'total_rating_count': 1002,
  'language_supports': [110185,
   110187,
   110181,
   110189,
   110191,
   110179,
   110195,
   110183,
   110193,
   210934,
   499232]},
 {'id': 1882,
  'first_release_date': 1378771200,
  'name': 'Amnesia: A Machine for Pigs',
  'rating': 67.23332558225488,
  'rating_count': 242,
  'summary': 'From the creators of Amnesia: The Dark Descent and Dear Esther comes a new first-person horrorgame that will drag you to the depths of greed power and madness. It will bury its snout into your ribs and it will eat your heart.',
  'total_rating': 69.92916279112744,
  'total_rating_count': 250,
  'language_supports': [180067,
   180068,
   180069,
   180070,
   180071,
   180072,
   180073,
   180074,
   180075,
   180076,
   180077,
   180078,
   180079,
   180080,
   180081,
   180082,
   180083,
   180084,
   180085,
   180086,
   180087,
   478939]},
 {'id': 1907,
  'first_release_date': 1456358400,
  'name': 'Grim Dawn',
  'rating': 73.39948224513111,
  'rating_count': 202,
  'summary': 'Enter an apocalyptic fantasy world where humanity is on the brink of extinction, iron is valued above gold and trust is hard earned. This ARPG features complex character development, hundreds of unique items, crafting and quests with choice & consequence.',
  'total_rating': 77.69974112256556,
  'total_rating_count': 206,
  'language_supports': [35083,
   35084,
   35085,
   35086,
   35087,
   35088,
   35089,
   35090,
   35091,
   35092,
   35093,
   35094,
   35095,
   35096,
   35097,
   35075,
   35077,
   35076,
   35072,
   35074,
   35078,
   35079,
   35080,
   35081,
   35082,
   35098,
   35073,
   475725]},
 {'id': 1910,
  'first_release_date': 1378252800,
  'name': 'Outlast',
  'rating': 77.1917288010899,
  'rating_count': 673,
  'summary': "Hell is an experiment you can't survive in Outlast, a first-person survival horror game developed by veterans of some of the biggest game franchises in history. As investigative journalist Miles Upshur, explore Mount Massive Asylum and try to survive long enough to discover its terrible secret... if you dare.",
  'total_rating': 77.18677349145403,
  'total_rating_count': 684,
  'language_supports': [480430,
   480433,
   480432,
   480431,
   480434,
   480429,
   480436,
   480435,
   480437,
   480438,
   1231956,
   1231960,
   1231952,
   1231957,
   1231955,
   1231954,
   1231953,
   1231961,
   1231962,
   1231963,
   1231964,
   1231965,
   1231966,
   1231967,
   1231958,
   1231959]},
 {'id': 1911,
  'first_release_date': 1382486400,
  'name': 'Path of Exile',
  'rating': 82.07996986204142,
  'rating_count': 478,
  'summary': 'You are an Exile, struggling to survive on the dark continent of Wraeclast, as you fight to earn power that will allow you to exact your revenge against those who wronged you. Created by hardcore gamers, Path of Exile is an online Action RPG set in a dark fantasy world.',
  'total_rating': 80.03998493102071,
  'total_rating_count': 482,
  'language_supports': [210073,
   210075,
   210078,
   210080,
   210082,
   210083,
   210084,
   489649,
   489650,
   489651,
   489652,
   489653,
   489654,
   489655,
   489656]},
 {'id': 1983,
  'first_release_date': 1311120000,
  'name': 'Bastion',
  'rating': 82.51652090634842,
  'rating_count': 739,
  'summary': 'A hack-and-slash RPG featuring a reactive narrator, various unlockable weapons, weapon upgrades, practice mini-games and optional difficulty modifiers, set in an imaginary world in the aftermath of an uncertain apocalypse, in which the player embodies a teenager with a troubled past as he and the narrator work together to rebuild the world out of a persisting hub called the Bastion.',
  'total_rating': 86.38326045317422,
  'total_rating_count': 747,
  'language_supports': [421567,
   421571,
   421568,
   421570,
   421569,
   421559,
   421560,
   421561,
   421562,
   421563,
   421564,
   421565,
   421566]},
 {'id': 1991,
  'first_release_date': 1334275200,
  'name': 'Fez',
  'rating': 81.2955952504785,
  'rating_count': 445,
  'summary': 'Gomez is a 2D creature living in a 2D world. Or is he? When the existence of a mysterious 3rd dimension is revealed to him, Gomez is sent out on a journey that will take him to the very end of time and space. Use your ability to navigate 3D structures from 4 distinct classic 2D perspectives. Explore a serene and beautiful open-ended world full of secrets, puzzles and hidden treasures. Unearth the mysteries of the past and discover the truth about reality and perception. Change your perspective and look at the world in a different way.',
  'total_rating': 83.39779762523925,
  'total_rating_count': 457,
  'language_supports': [30552,
   30554,
   30556,
   30558,
   30560,
   30562,
   30564,
   30565,
   30566,
   477267]},
 {'id': 2000,
  'first_release_date': 875059200,
  'name': 'Postal',
  'rating': 66.62700113186726,
  'rating_count': 91,

In [220]:
df_games_igdb = pd.DataFrame(res)
df_games_igdb.isna().sum()

id                     0
first_release_date     0
name                   0
rating                15
rating_count          15
summary                0
total_rating          15
total_rating_count    15
language_supports      7
dtype: int64

In [221]:
df_games_igdb

,id,first_release_date,name,rating,rating_count,summary,total_rating,total_rating_count,language_supports
0,111,1283904000,Amnesia: The Dark Descent,77.953339,523.0,Amnesia: The Dark Descent is a survival horror...,83.476670,525.0,"[478453, 478456, 478457, 478454, 478455, 47845..."
1,232,942192000,Half-Life: Opposing Force,79.914312,386.0,Opposing Force returns to the same setting as ...,74.957156,387.0,"[604211, 604212, 604213, 604214]"
2,527,1321920000,Serious Sam 3: BFE,69.983462,172.0,Serious Sam 3: BFE is a first-person action sh...,70.408398,178.0,"[409265, 409267, 409269, 409272, 409273, 40927..."
3,576,1294704000,DC Universe Online,63.259002,65.0,DC Universe Online is a free-to-play superhero...,68.486644,72.0,"[137259, 137260, 137261, 137262, 137263, 75826..."
4,787,1128988800,Serious Sam II,71.570333,182.0,The iconic Serious Sam brings his trademark re...,74.951833,185.0,"[534874, 534875, 534873]"
...,...,...,...,...,...,...,...,...,...
494,281275,1703721600,Buckshot Roulette,77.749449,138.0,Buckshot Roulette is a tabletop horror game th...,78.874724,139.0,"[873748, 873749, 909410, 909411, 909412, 90941..."
495,309862,1774915200,TCG Card Shop Simulator,78.356938,22.0,Open your own local game store. Stock shelves ...,78.356938,22.0,"[1045833, 1063105, 1063106, 1063107, 1063108, ..."
496,311540,1723161600,Supermarket Together,84.839384,30.0,The multiplayer supermarket has arrived to you...,84.839384,30.0,"[1098181, 1098182, 1057452, 1057453, 1057454, ..."
497,317695,1738022400,Liar's Bar,69.880518,26.0,Liar's Bar is a 2-4 player multiplayer decepti...,69.880518,26.0,"[1093114, 1093118, 1093116, 1093117, 1093115, ..."
498,319271,1728604800,Webfishing,76.078875,26.0,Webfishing is a multiplayer chatroom-focused f...,76.078875,26.0,[1101646]

Пока что особо проблем с данными нет, есть несколько столбцов, которых нужно немного преобразовать (можно сделать, когда соберем полный датасет), но в общем и целом, с такими данными уже можно работать